name: Deploy to Private VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Using Docker Compose to spin up the environment
      - name: Deploy with Docker Compose
        run: |
          echo "Building and deploying application..."
          # Disable BuildKit to workaround LXC permission issues on Hostinger
          export DOCKER_BUILDKIT=0
          export COMPOSE_DOCKER_CLI_BUILD=0
          
          # Pull latest images and build local ones with sudo
          sudo -E docker compose -f infra/docker-compose.yml build
          # Restart services safely
          sudo -E docker compose -f infra/docker-compose.yml up -d
          
          # Clean up dangling images to save space on VM
          sudo docker image prune -f
          echo "Deployment successful."
